<?php if (! defined('BASEPATH')) { exit('No direct script access allowed'); } ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo html_escape($page_title); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?php echo base_url(); ?>assets/backend/image/rockfm-logo-ico.png" type="image/png">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;600;700;800&display=swap');
        :root{--ink:#14233b;--muted:rgba(20,35,59,.66);--brand-a:#d70a7c;--brand-b:#1d9bf0;--brand-deep:#5a1687;--line:rgba(20,35,59,.1)}
        *{box-sizing:border-box}body{margin:0;font-family:"Plus Jakarta Sans","Segoe UI",sans-serif;color:var(--ink);background:radial-gradient(circle at top left,rgba(215,10,124,.14),transparent 26%),radial-gradient(circle at top right,rgba(29,155,240,.14),transparent 26%),linear-gradient(180deg,#fbf7fd 0%,#f4f8ff 100%)}
        .app{max-width:1180px;margin:0 auto;padding:28px 20px 64px}.topbar{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap;margin-bottom:22px}.identity{display:flex;flex-direction:column;gap:10px}
        .brand{display:inline-flex;align-items:center;padding:10px 14px;border-radius:999px;background:linear-gradient(135deg,rgba(215,10,124,.12),rgba(29,155,240,.12));color:var(--brand-deep);font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.support{font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted)}
        .topbar-right{display:flex;gap:12px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 20px;border-radius:14px;font-weight:800;text-decoration:none}.btn-primary{background:linear-gradient(135deg,var(--brand-a) 0%,var(--brand-b) 100%);color:#fff}.btn-secondary{background:#fff;color:var(--ink);border:1px solid var(--line)}
        .hero,.panel{background:#fff;border:1px solid var(--line);border-radius:24px;box-shadow:0 24px 64px rgba(9,44,51,.1)}.hero{display:grid;grid-template-columns:1.15fr .85fr;gap:18px;padding:28px;margin-bottom:18px}
        h1{margin:8px 0 10px;font-size:48px;line-height:.95;letter-spacing:-.05em}p{color:var(--muted);line-height:1.65}.meta{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.chip{display:inline-flex;align-items:center;padding:10px 14px;border-radius:999px;background:linear-gradient(135deg,rgba(215,10,124,.08),rgba(29,155,240,.08));color:var(--brand-deep);font-size:12px;font-weight:800}
        .stats{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.stat{padding:18px;border-radius:20px;background:linear-gradient(135deg,var(--brand-a) 0%,var(--brand-b) 100%);color:#fff}.stat span{display:block;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.74);margin-bottom:8px}.stat strong{font-size:28px}
        .panel{padding:24px}table{width:100%;border-collapse:collapse}th,td{padding:16px 12px;text-align:left;border-bottom:1px solid rgba(9,44,51,.08)}th{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:rgba(9,44,51,.58)}.actions{display:flex;gap:10px;flex-wrap:wrap}.small{min-height:38px;padding:0 14px;font-size:13px}.empty{padding:36px;text-align:center;border:1px dashed rgba(9,44,51,.16);border-radius:20px;background:#f8fcfc}@media (max-width:960px){.hero,.stats{grid-template-columns:1fr}}
    </style>
</head>
<body>
<div class="app"><div class="topbar"><div class="identity"><span class="brand">Liquid CP</span><span class="support">By Liquid Intelligent Technologies Zambia</span></div><div class="topbar-right"><a class="btn btn-primary" href="<?php echo html_escape($studio_url); ?>">New estimate</a><a class="btn btn-secondary" href="<?php echo html_escape($logout_url); ?>">Sign out</a></div></div>
<section class="hero"><div><h1><?php echo $is_admin_viewer ? 'Operations view of saved estimates.' : 'Your saved estimates, ready to resume.'; ?></h1><p><?php echo $is_admin_viewer ? 'This dashboard is showing the full estimate set because you are signed in with an admin account.' : 'Return to previous quotations, open shared PDFs, or start a new estimate from a clean studio flow.'; ?></p><div class="meta"><span class="chip"><?php echo html_escape($user['login']); ?></span><span class="chip"><?php echo html_escape($user['mail']); ?></span><span class="chip"><?php echo $is_admin_viewer ? 'Admin visibility' : 'Private estimate list'; ?></span></div></div><div class="stats"><div class="stat"><span>Visible estimates</span><strong><?php echo number_format(count($quotes)); ?></strong></div><div class="stat"><span>Mode</span><strong><?php echo $is_admin_viewer ? 'All records' : 'Owner only'; ?></strong></div></div></section>
<section class="panel"><?php if (empty($quotes)) { ?><div class="empty"><h2 style="margin-top:0;">Create your first estimate</h2><p>Your dashboard stays empty until you save a quotation snapshot.</p><a class="btn btn-primary" href="<?php echo html_escape($studio_url); ?>">Open estimate studio</a></div><?php } else { ?><table><thead><tr><th>Quote</th><th>Client</th><th>Title</th><th>Created</th><th>Total Due</th><th>Actions</th></tr></thead><tbody><?php foreach ($quotes as $quote) { ?><tr><td><?php echo html_escape($quote['quote_number'] ?: 'Draft'); ?></td><td><?php echo html_escape($quote['client_name']); ?></td><td><?php echo html_escape($quote['quote_title']); ?></td><td><?php echo html_escape($quote['created_at']); ?></td><td><?php echo number_format((float) $quote['total_due'], 2); ?> ZMW</td><td><div class="actions"><a class="btn btn-secondary small" href="<?php echo site_url('liquidcp/quote/' . $quote['id']); ?>" target="_blank">Open</a><a class="btn btn-secondary small" href="<?php echo site_url('liquidcp/pdf/' . $quote['id']); ?>" target="_blank">PDF</a></div></td></tr><?php } ?></tbody></table><?php } ?></section></div>
</body>
</html>
