<?php if (! defined('BASEPATH')) { exit('No direct script access allowed'); } ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo html_escape($quote['quote_number']); ?> | Liquid CP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?php echo base_url(); ?>assets/backend/image/rockfm-logo-ico.png" type="image/png">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;600;700;800&display=swap');
        :root{--ink:#14233b;--muted:rgba(20,35,59,.66);--brand-a:#d70a7c;--brand-b:#1d9bf0;--brand-deep:#5a1687;--line:rgba(20,35,59,.1)}
        *{box-sizing:border-box}body{margin:0;font-family:"Plus Jakarta Sans","Segoe UI",sans-serif;color:var(--ink);background:radial-gradient(circle at top left,rgba(215,10,124,.14),transparent 28%),radial-gradient(circle at bottom right,rgba(29,155,240,.14),transparent 24%),linear-gradient(180deg,#fbf7fd 0%,#f4f8ff 100%)}
        .quote-shell{max-width:1160px;margin:0 auto;padding:28px 20px 56px}.quote-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;margin-bottom:20px}
        .brand{display:inline-flex;align-items:center;padding:10px 14px;border-radius:999px;background:linear-gradient(135deg,rgba(215,10,124,.12),rgba(29,155,240,.12));color:var(--brand-deep);font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.support{margin-top:10px;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted)}
        .actions{display:flex;gap:12px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 20px;border-radius:14px;font-weight:800;text-decoration:none}.btn-primary{background:linear-gradient(135deg,var(--brand-a) 0%,var(--brand-b) 100%);color:#fff}.btn-secondary{background:#fff;color:var(--ink);border:1px solid rgba(20,35,59,.12)}
        .hero,.panel{background:#fff;border:1px solid var(--line);border-radius:24px;box-shadow:0 24px 64px rgba(9,44,51,.1)}.hero{padding:30px;margin-bottom:18px}
        h1{margin:16px 0 10px;font-size:54px;line-height:.92;letter-spacing:-.05em}.subtitle{font-size:18px;color:var(--muted);margin:0 0 12px}.chips{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.chip{display:inline-flex;align-items:center;padding:10px 14px;border-radius:999px;background:linear-gradient(135deg,rgba(215,10,124,.08),rgba(29,155,240,.08));color:var(--brand-deep);font-size:12px;font-weight:800}
        .metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:22px}.metric{padding:18px;border-radius:18px;border:1px solid rgba(9,44,51,.08);background:linear-gradient(180deg,#fff,#f7fcfc)}.metric span{display:block;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:rgba(9,44,51,.58);margin-bottom:8px}.metric strong{font-size:24px}
        .layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:18px}.panel{padding:20px}.panel h2,.panel h3{margin-top:0}.category{overflow:hidden;border-radius:20px;border:1px solid rgba(9,44,51,.08);background:linear-gradient(180deg,#fff,#f7fcfc);margin-bottom:14px}.category-head{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:16px 18px;background:#f4fbfb;border-bottom:1px solid rgba(9,44,51,.08)}
        table{width:100%;border-collapse:collapse}th,td{padding:14px 16px;border-bottom:1px solid rgba(9,44,51,.06);text-align:left}th{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:rgba(9,44,51,.56)}.sidebar{display:grid;gap:14px}.label{display:block;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:rgba(9,44,51,.58);margin-bottom:6px}.value{font-weight:700}ul{margin:0;padding-left:18px;color:var(--muted)}@media (max-width:960px){.layout,.metrics{grid-template-columns:1fr}h1{font-size:40px}}
    </style>
</head>
<body>
<div class="quote-shell"><div class="quote-top"><div><span class="brand">Liquid CP Quotation</span><div class="support">By Liquid Intelligent Technologies Zambia</div></div><div class="actions"><a class="btn btn-primary" target="_blank" href="<?php echo site_url('liquidcp/pdf/' . $quote['id']); ?>">Open PDF</a><a class="btn btn-secondary" target="_blank" href="<?php echo site_url('admin/liquidcp/quotation/' . $quote['id']); ?>">Admin view</a></div></div>
<section class="hero"><h1><?php echo html_escape($quote['quote_number']); ?></h1><p class="subtitle"><?php echo html_escape($quote['quote_title']); ?></p><p><?php echo html_escape($quote['client_name']); ?> | <?php echo html_escape($quote['client_email']); ?> | <?php echo html_escape($quote['company_name']); ?></p><div class="chips"><span class="chip">Ruleset <?php echo html_escape($quote['rule_set_version']); ?></span><span class="chip">Engine <?php echo html_escape($quote['engine_version']); ?></span><span class="chip">Saved snapshot</span></div><div class="metrics"><div class="metric"><span>Total due</span><strong><?php echo number_format($quote['response']['total_due'], 2); ?> ZMW</strong></div><div class="metric"><span>Build cost</span><strong><?php echo number_format($quote['response']['build_cost'], 2); ?> ZMW</strong></div><div class="metric"><span>Net build cost</span><strong><?php echo number_format($quote['response']['net_build_cost'], 2); ?> ZMW</strong></div><div class="metric"><span>ROI years</span><strong><?php echo $quote['response']['roi_years'] === null ? 'N/A' : number_format($quote['response']['roi_years'], 3); ?></strong></div></div></section>
<div class="layout"><div><?php foreach ($quote['response']['line_items'] as $category => $items) { ?><div class="category"><div class="category-head"><strong><?php echo ucfirst($category); ?></strong><div><span class="label">Category total</span><strong><?php echo number_format(array_sum(array_column($items, 'amount')), 2); ?> ZMW</strong></div></div><div class="table-responsive"><table><thead><tr><th>Item</th><th>Quantity</th><th>Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody><?php foreach ($items as $item) { ?><tr><td><?php echo html_escape($item['label']); ?></td><td><?php echo html_escape($item['quantity']); ?></td><td><?php echo html_escape($item['unit']); ?></td><td><?php echo number_format($item['unit_rate'], 2); ?></td><td><?php echo number_format($item['amount'], 2); ?></td></tr><?php } ?></tbody></table></div></div><?php } ?></div>
<aside class="sidebar"><div class="panel"><h3>Phase 1 note</h3><p><?php echo html_escape($prototype_disclaimer); ?></p></div><div class="panel"><h3>Snapshot details</h3><p><span class="label">PDF path</span><span class="value"><?php echo html_escape($quote['pdf_path'] ?: 'Not generated yet'); ?></span></p><p><span class="label">Build profile</span><span class="value"><?php echo html_escape($quote['input']['build_profile']); ?></span></p><p><span class="label">Customer NRC</span><span class="value"><?php echo number_format($quote['input']['customer_nrc'], 2); ?> ZMW</span></p><p><span class="label">Customer MRC</span><span class="value"><?php echo number_format($quote['input']['customer_mrc'], 2); ?> ZMW</span></p><p><span class="label">Exchange rate</span><span class="value"><?php echo number_format($quote['input']['exchange_rate'], 2); ?></span></p></div><div class="panel"><h3>Route inputs</h3><p><span class="label">New aerial</span><span class="value"><?php echo number_format($quote['input']['distance_new_aerial'], 2); ?> m</span></p><p><span class="label">New underground</span><span class="value"><?php echo number_format($quote['input']['distance_new_underground'], 2); ?> m</span></p><p><span class="label">Existing aerial</span><span class="value"><?php echo number_format($quote['input']['distance_existing_aerial'], 2); ?> m</span></p><p><span class="label">Existing duct</span><span class="value"><?php echo number_format($quote['input']['distance_existing_duct'], 2); ?> m</span></p></div><div class="panel"><h3>Warnings</h3><ul><?php if (empty($quote['response']['warnings'])) { ?><li>No warnings were returned by the engine.</li><?php } else { ?><?php foreach ($quote['response']['warnings'] as $warning) { ?><li><?php echo html_escape($warning); ?></li><?php } ?><?php } ?></ul></div></aside></div></div>
</body>
</html>
